BEGIN;

UPDATE "Vocab"."File_Tye" SET "Name" = 'Chemical Crosslinks from Experiments', "Table_Name" = 'ihm_cross_link_list' WHERE "Description" = 'List of distance restraints derived from chemical crosslinking experiments';
UPDATE "Vocab"."File_Tye" SET "Name" = 'Chemical Crosslinking Restraints Applied in the Modeling', "Table_Name" = 'ihm_cross_link_restraint' WHERE "Description" = 'Chemical crosslinking restraints used in modeling';
UPDATE "Vocab"."File_Tye" SET "Name" = 'Chemical Crosslink Restraint Results', "Table_Name" = 'ihm_cross_link_result' WHERE "Description" = 'Results of the crosslinking restraints in integrative modeling';
UPDATE "Vocab"."File_Tye" SET "Name" = 'Chemical Crosslink Restraint Result Parameters', "Table_Name" = 'ihm_cross_link_result_parameters' WHERE "Description" = 'Parameters related to the results of crosslinking restraints';
UPDATE "Vocab"."File_Tye" SET "Name" = 'Predicted Contact Restraints', "Table_Name" = 'ihm_predicted_contact_restraint' WHERE "Description" = 'Restraints derived from predicted contacts';
UPDATE "Vocab"."File_Tye" SET "Name" = 'Hydroxyl Radical Footprinting Restraints', "Table_Name" = 'ihm_hydroxyl_radical_fp_restraint' WHERE "Description" = 'Data from hydroxyl radical footprinting experiments used as restraint in modeling';
UPDATE "Vocab"."File_Tye" SET "Name" = 'Molecular Features used in Generic Restraints', "Table_Name" = 'ihm_feature_list' WHERE "Description" = 'List of features (atoms, residues, residue ranges, non-polymeric entities, pseudo sites) used in generic distance restraints';
UPDATE "Vocab"."File_Tye" SET "Name" = 'Molecular Features Comprising of Pseudo Sites', "Table_Name" = 'ihm_pseudo_site_feature' WHERE "Description" = 'Details of pseudo positions used in generic distance restraints';
UPDATE "Vocab"."File_Tye" SET "Name" = 'Molecular Features Comprising of Polymeric Atoms', "Table_Name" = 'ihm_poly_atom_feature' WHERE "Description" = 'Details of atomic features of polymeric entities';
UPDATE "Vocab"."File_Tye" SET "Name" = 'Molecular Features Comprising of Polymeric Residues', "Table_Name" = 'ihm_poly_residue_feature' WHERE "Description" = 'Details of polymeric residue features';
UPDATE "Vocab"."File_Tye" SET "Name" = 'Molecular Features Comprising of Non-polymeric Entities', "Table_Name" = 'ihm_non_poly_feature' WHERE "Description" = 'Details of non-polymeric (ligand) features';
UPDATE "Vocab"."File_Tye" SET "Name" = 'Molecular Features Comprising of Polymeric Residues at Interfaces', "Table_Name" = 'ihm_interface_residue_feature' WHERE "Description" = 'Details of residues at the binding interface';
UPDATE "Vocab"."File_Tye" SET "Name" = 'Generic Distance Restraints Between Molecular Features', "Table_Name" = 'ihm_derived_distance_restraint' WHERE "Description" = 'Generic distance restraints between features (atoms, residues, non-polymeric entities, pseudo sites)';
UPDATE "Vocab"."File_Tye" SET "Name" = 'Probes Attached to Residues in Polymeric Entities', "Table_Name" = 'ihm_poly_probe_conjugate' WHERE "Description" = 'Probes that are covalently attached to residues in polymeric entities';
UPDATE "Vocab"."File_Tye" SET "Name" = 'Distance Restraints between Geometric Objects and Molecular Features', "Table_Name" = 'ihm_geometric_object_distance_restraint' WHERE "Description" = 'Generic distance restraints between geometric objects and molecular features (atoms, residues etc.';
UPDATE "Vocab"."File_Tye" SET "Name" = 'Residue Positions in Polymeric Entities where Probes are Attached', "Table_Name" = 'ihm_poly_probe_position' WHERE "Description" = 'Specific residue positions in the polymeric entity where probes are covalently attached';
UPDATE "Vocab"."File_Tye" SET "Name" = 'Non-polymeric Entities used as Probes', "Table_Name" = 'ihm_ligand_probe' WHERE "Description" = 'Non-covalently interacting ligands used as probes';
UPDATE "Vocab"."File_Tye" SET "Name" = 'Chemical Crosslinks with Pseudo Sites', "Table_Name" = 'ihm_cross_link_pseudo_site' WHERE "Description" = 'Details of pseudo sites involved in crosslinks';
UPDATE "Vocab"."File_Tye" SET "Name" = 'HD Exchange Restraints', "Table_Name" = 'ihm_hdx_restraint' WHERE "Description" = 'Details of restraint derived from hydrogen-deuterium exchange experiments';
UPDATE "Vocab"."File_Tye" SET "Name" = 'Pseudo Site Coordinates', "Table_Name" = 'ihm_pseudo_site' WHERE "Description" = 'Details of pseudo sites that may be used in restraints or in model representation';
UPDATE "Vocab"."File_Tye" SET "Name" = 'Angle Restraints Between Molecular Features', "Table_Name" = 'ihm_derived_angle_restraint' WHERE "Description" = 'Generic angle restraints between features (atoms, residues, non-polymeric entities, pseudo sites)';
UPDATE "Vocab"."File_Tye" SET "Name" = 'Dihedral Restraints Between Molecular Features', "Table_Name" = 'ihm_derived_dihedral_restraint' WHERE "Description" = 'Generic dihedral restraints between features (atoms, residues, non-polymeric entities, pseudo sites)';

UPDATE "PDB"."ihm_entity_poly_segment" A set "Entity_Poly_Seq_RID_Begin" = (select "RID" from "PDB"."entity_poly_seq" B where A.structure_id = B.structure_id and A.comp_id_begin = B.mon_id and A.entity_id = B.entity_id and A.seq_id_begin = B.num);
UPDATE "PDB"."ihm_entity_poly_segment" A set "Entity_Poly_Seq_RID_End" = (select "RID" from "PDB"."entity_poly_seq" B where A.structure_id = B.structure_id and A.seq_id_end = B.num and A.entity_id = B.entity_id and A.comp_id_end = B.mon_id);

INSERT INTO "PDB"."Entry_Related_File_Templates" ("File_Type", "File_URL", "File_Name", "File_MD5", "File_Bytes", "Description") VALUES('Chemical Crosslinks from Experiments', '/hatrac/pdb/templates/Chemical-Crosslinks-from-Experiments.csv:JFTFK6S36QDQ2Q3EFGFF4W2EEU', 'Chemical-Crosslinks-from-Experiments.csv', 'd1acf49b6681149dd440e3eb835731a8', 183, 'List of distance restraints derived from chemical crosslinking experiments');
INSERT INTO "PDB"."Entry_Related_File_Templates" ("File_Type", "File_URL", "File_Name", "File_MD5", "File_Bytes", "Description") VALUES('Chemical Crosslinking Restraints Applied in the Modeling', '/hatrac/pdb/templates/Chemical-Crosslinking-Restraints-Applied-in-the-Modeling.csv:EH2Z2KOXHKZ2BBBGSQ37UCYBDM', 'Chemical-Crosslinking-Restraints-Applied-in-the-Modeling.csv', '91b60374128f66f8de11689718d30a10', 228, 'Chemical crosslinking restraints used in modeling');
INSERT INTO "PDB"."Entry_Related_File_Templates" ("File_Type", "File_URL", "File_Name", "File_MD5", "File_Bytes", "Description") VALUES('Chemical Crosslink Restraint Results', '/hatrac/pdb/templates/Chemical-Crosslink-Restraint-Results.csv:ZXNGP56LS2ZRL2F7QYAAPLTK2I', 'Chemical-Crosslink-Restraint-Results.csv', '2145a28338b9d13ad5a18fb20b22743b', 82, 'Results of the crosslinking restraints in integrative modeling');
INSERT INTO "PDB"."Entry_Related_File_Templates" ("File_Type", "File_URL", "File_Name", "File_MD5", "File_Bytes", "Description") VALUES('Chemical Crosslink Restraint Result Parameters', '/hatrac/pdb/templates/Chemical-Crosslink-Restraint-Result-Parameters.csv:WC74S7AGI6LTGYHYROP5LOOEDM', 'Chemical-Crosslink-Restraint-Result-Parameters.csv', 'e3ce37ec609b7c52e40ef212ee53d4a2', 45, 'Parameters related to the results of crosslinking restraints');
INSERT INTO "PDB"."Entry_Related_File_Templates" ("File_Type", "File_URL", "File_Name", "File_MD5", "File_Bytes", "Description") VALUES('Predicted Contact Restraints', '/hatrac/pdb/templates/Predicted-Contact-Restraints.csv:4TTOJN2TIJDDV7V43TN4R77PNE', 'Predicted-Contact-Restraints.csv', 'd3c5f4558972c6b5c715312cf3e2f06a', 273, 'Restraints derived from predicted contacts');
INSERT INTO "PDB"."Entry_Related_File_Templates" ("File_Type", "File_URL", "File_Name", "File_MD5", "File_Bytes", "Description") VALUES('Hydroxyl Radical Footprinting Restraints', '/hatrac/pdb/templates/Hydroxyl-Radical-Footprinting-Restraints.csv:ZJNXUXHCC6LEZ2ZM6HFENUBWNM', 'Hydroxyl-Radical-Footprinting-Restraints.csv', 'cde0fc0bf27e9a6957c3227d1dee5151', 149, 'Data from hydroxyl radical footprinting experiments used as restraint in modeling');
INSERT INTO "PDB"."Entry_Related_File_Templates" ("File_Type", "File_URL", "File_Name", "File_MD5", "File_Bytes", "Description") VALUES('Molecular Features used in Generic Restraints', '/hatrac/pdb/templates/Molecular-Features-used-in-Generic-Restraints.csv:Z2EZTQ44U6NWRVB7CO2E44WEXY', 'Molecular-Features-used-in-Generic-Restraints.csv', '946b90a719aabe7d4c8e9b68c58f5304', 44, 'List of features (atoms, residues, residue ranges, non-polymeric entities, pseudo sites) used in generic distance restraints');
INSERT INTO "PDB"."Entry_Related_File_Templates" ("File_Type", "File_URL", "File_Name", "File_MD5", "File_Bytes", "Description") VALUES('Molecular Features Comprising of Pseudo Sites', '/hatrac/pdb/templates/Molecular-Features-Comprising-of-Pseudo-Sites.csv:4GNCQ6X5RT4D3AM5PVDFVVFTLU', 'Molecular-Features-Comprising-of-Pseudo-Sites.csv', '719e72770ea0e6272b1057ae27454d04', 26, 'Details of pseudo positions used in generic distance restraints');
INSERT INTO "PDB"."Entry_Related_File_Templates" ("File_Type", "File_URL", "File_Name", "File_MD5", "File_Bytes", "Description") VALUES('Molecular Features Comprising of Polymeric Atoms', '/hatrac/pdb/templates/Molecular-Features-Comprising-of-Polymeric-Atoms.csv:W5EKH6UIH36QRPFN47A2CQURZA', 'Molecular-Features-Comprising-of-Polymeric-Atoms.csv', '2161e3f07b05d624961129c7f5f54a8e', 63, 'Details of atomic features of polymeric entities');
INSERT INTO "PDB"."Entry_Related_File_Templates" ("File_Type", "File_URL", "File_Name", "File_MD5", "File_Bytes", "Description") VALUES('Molecular Features Comprising of Polymeric Residues', '/hatrac/pdb/templates/Molecular-Features-Comprising-of-Polymeric-Residues.csv:ZHWP5IZ7CKZFDNVZFAYC6SE2XY', 'Molecular-Features-Comprising-of-Polymeric-Residues.csv', '6a85714f9d9b4a409efe9b546414114a', 148, 'Details of polymeric residue features');
INSERT INTO "PDB"."Entry_Related_File_Templates" ("File_Type", "File_URL", "File_Name", "File_MD5", "File_Bytes", "Description") VALUES('Molecular Features Comprising of Non-polymeric Entities', '/hatrac/pdb/templates/Molecular-Features-Comprising-of-Non-polymeric-Entities.csv:J2IZ2I64AQDVANCB7JVTSPIONI', 'Molecular-Features-Comprising-of-Non-polymeric-Entities.csv', '8621929c89ffce073472ccdf0124683d', 56, 'Details of non-polymeric (ligand) features');
INSERT INTO "PDB"."Entry_Related_File_Templates" ("File_Type", "File_URL", "File_Name", "File_MD5", "File_Bytes", "Description") VALUES('Molecular Features Comprising of Polymeric Residues at Interfaces', '/hatrac/pdb/templates/Molecular-Features-Comprising-of-Polymeric-Residues-at-Interfaces.csv:YZ2KXSGZDS6D6WHBR55TDQTPOQ', 'Molecular-Features-Comprising-of-Polymeric-Residues-at-Interfaces.csv', 'a293f0a570904f84b244adcc0f1af81a', 96, 'Details of residues at the binding interface');
INSERT INTO "PDB"."Entry_Related_File_Templates" ("File_Type", "File_URL", "File_Name", "File_MD5", "File_Bytes", "Description") VALUES('Generic Distance Restraints Between Molecular Features', '/hatrac/pdb/templates/Generic-Distance-Restraints-Between-Molecular-Features.csv:PZGXFE63QMTC3P7NPVSAEL2OXY', 'Generic-Distance-Restraints-Between-Molecular-Features.csv', 'b42b41f8cbd6e0b2ad45db9a59b7ddfc', 282, 'Generic distance restraints between features (atoms, residues, non-polymeric entities, pseudo sites)');
INSERT INTO "PDB"."Entry_Related_File_Templates" ("File_Type", "File_URL", "File_Name", "File_MD5", "File_Bytes", "Description") VALUES('Distance Restraints between Geometric Objects and Molecular Features', '/hatrac/pdb/templates/Distance-Restraints-between-Geometric-Objects-and-Molecular-Features.csv:W3SQB2YSU6T65H2BEZ33OGB2BA', 'Distance-Restraints-between-Geometric-Objects-and-Molecular-Features.csv', '35a3f207a95b1e05eb31492cd4ed2eee', 243, 'Generic distance restraints between geometric objects and molecular features (atoms, residues etc.)');
INSERT INTO "PDB"."Entry_Related_File_Templates" ("File_Type", "File_URL", "File_Name", "File_MD5", "File_Bytes", "Description") VALUES('Residue Positions in Polymeric Entities where Probes are Attached', '/hatrac/pdb/templates/Residue-Positions-in-Polymeric-Entities-where-Probes-are-Attached.csv:PZCGCTCGTECQJDK33EOZCENE7Y', 'Residue-Positions-in-Polymeric-Entities-where-Probes-are-Attached.csv', 'c53eee42650f9894e7f308c4fd538e59', 144, 'Specific residue positions in the polymeric entity where probes are covalently attached');
INSERT INTO "PDB"."Entry_Related_File_Templates" ("File_Type", "File_URL", "File_Name", "File_MD5", "File_Bytes", "Description") VALUES('Probes Attached to Residues in Polymeric Entities', '/hatrac/pdb/templates/Probes-Attached-to-Residues-in-Polymeric-Entities.csv:5IZNG42T4ZCR23VGQTFBSQ2M7I', 'Probes-Attached-to-Residues-in-Polymeric-Entities.csv', '5968e182dd694f6551d424f5c8e86414', 121, 'Probes that are covalently attached to residues in polymeric entities');
INSERT INTO "PDB"."Entry_Related_File_Templates" ("File_Type", "File_URL", "File_Name", "File_MD5", "File_Bytes", "Description") VALUES('Non-polymeric Entities used as Probes', '/hatrac/pdb/templates/Non-polymeric-Entities-used-as-Probes.csv:I3JT23EGC3YOCXHNCP326RWTQE', 'Non-polymeric-Entities-used-as-Probes.csv', 'fa9aea7a3571d26c07fe60aa3aa1bbce', 43, 'Non-covalently interacting ligands used as probes');
INSERT INTO "PDB"."Entry_Related_File_Templates" ("File_Type", "File_URL", "File_Name", "File_MD5", "File_Bytes", "Description") VALUES('Pseudo Site Coordinates', '/hatrac/pdb/templates/Pseudo-Site-Coordinates.csv:WGRX3K4X5N4KUVX4MMADYKINRI', 'Pseudo-Site-Coordinates.csv', '7526260ed8d74a90ee0aa0d52119fd55', 46, 'Details of pseudo sites used in restraints or model representation');
INSERT INTO "PDB"."Entry_Related_File_Templates" ("File_Type", "File_URL", "File_Name", "File_MD5", "File_Bytes", "Description") VALUES('Chemical Crosslinks with Pseudo Sites', '/hatrac/pdb/templates/Chemical-Crosslinks-with-Pseudo-Sites.csv:SCC3OYLAJEDY4GNG5JZR6MM73M', 'Chemical-Crosslinks-with-Pseudo-Sites.csv', '5ae8918247437beb363b945e90300aa7', 59, 'Details of chemical crosslinks involving pseudo sites');
INSERT INTO "PDB"."Entry_Related_File_Templates" ("File_Type", "File_URL", "File_Name", "File_MD5", "File_Bytes", "Description") VALUES('HD Exchange Restraints', '/hatrac/pdb/templates/HD-Exchange-Restraints.csv:BGYHFHS3ICNVJKMNU46OXBNFXI', 'HD-Exchange-Restraints.csv', '7af3ea266e448e16bd2e4f96527fb5d5', 56, 'Details of hydrogen/deuterium exchange restraints derived from experiments');
INSERT INTO "PDB"."Entry_Related_File_Templates" ("File_Type", "File_URL", "File_Name", "File_MD5", "File_Bytes", "Description") VALUES('Angle Restraints Between Molecular Features', '/hatrac/pdb/templates/Angle-Restraints-Between-Molecular-Features.csv:7ZOZLNOHFODE5SMPWPSKPH3L4E', 'Angle-Restraints-Between-Molecular-Features.csv', 'f1b9a088cf4fdd7d68e2f329c7a3d77f', 241, 'Generic angle restraints between features (atoms, residues, non-polymeric entities, pseudo sites)');
INSERT INTO "PDB"."Entry_Related_File_Templates" ("File_Type", "File_URL", "File_Name", "File_MD5", "File_Bytes", "Description") VALUES('Dihedral Restraints Between Molecular Features', '/hatrac/pdb/templates/Dihedral-Restraints-Between-Molecular-Features.csv:BMHPM4MM4I3HR76UCDSSQKSZ4I', 'Dihedral-Restraints-Between-Molecular-Features.csv', 'd5e859dccecf6c8f87841d5db0320258', 272, 'Generic dihedral restraints between molecular features (atoms, residues, non-polymeric entities, pseudo sites)');

COMMIT;

