#!/bin/bash

. /usr/local/sbin/pdb-software-lib.sh

job_tasks=(
    "derivapy_pull_checkout"
    "pdb_www_pull_checkout"
    "python_ihm_pull_checkout 1.0"
    "derivapy_install"
    "pdb_processing_install"
    "python_ihm_install"
    "require service pdb_dev_processing_worker start"
    "require service pdb_staging_processing_worker start"
)

cron_run "hourly-update" "${job_tasks[@]}"

